In [1]:
import geopandas as gpd
import matplotlib.pyplot as plt
from shapely.geometry import Point
import pandas as pd

In [2]:
url = "https://naciscdn.org/naturalearth/110m/cultural/ne_110m_admin_0_countries.zip"
world = gpd.read_file(url)
usa = world[world['ADMIN'] == 'United States of America']

In [4]:
all_reports = pd.read_csv('/Users/jimnguyen/IRMII/SCS_API/data/All_SCS_Reports.csv',low_memory = False)

In [5]:
all_reports['BEGIN'] = (
    all_reports['BEGIN_YEARMONTH'].astype(str)
    + all_reports['BEGIN_DAY'].astype(str).str.zfill(2)
    + all_reports['BEGIN_TIME'].astype(str).str.zfill(4)
).astype(int)

In [6]:
all_reports['END'] = (
    all_reports['END_YEARMONTH'].astype(str)
    + all_reports['END_DAY'].astype(str).str.zfill(2)   
    + all_reports['END_TIME'].astype(str).str.zfill(4) 
).astype(int)

In [7]:
reports = all_reports[['BEGIN','END','EVENT_TYPE','BEGIN_LAT','BEGIN_LON','END_LAT','END_LON','MAGNITUDE']]

In [8]:
hail_reports = reports[reports['EVENT_TYPE']== 'Hail']
hail_reports

,BEGIN,END,EVENT_TYPE,BEGIN_LAT,BEGIN_LON,END_LAT,END_LON,MAGNITUDE
1865,195509221610,195509221610,Hail,38.70,-94.08,NaN,NaN,1.50
1868,195507191330,195507191330,Hail,30.50,-87.90,NaN,NaN,0.75
1875,195510281645,195510281645,Hail,33.28,-86.78,NaN,NaN,2.00
1879,195506121700,195506121700,Hail,37.08,-107.80,NaN,NaN,1.00
1882,195505071845,195505071845,Hail,37.08,-94.68,NaN,NaN,1.75
...,...,...,...,...,...,...,...,...
1168917,202407061246,202407061246,Hail,40.58,-99.38,40.58,-99.38,1.75
1168918,202407061520,202407061520,Hail,40.32,-98.90,40.32,-98.90,0.75
1168944,202407061255,202407061255,Hail,40.55,-99.32,40.55,-99.32,2.00
1168953,202407061258,202407061258,Hail,40.71,-99.88,40.71,-99.88,1.00
1168955,202407061645,202407061645,Hail,40.54,-97.59,40.54,-97.59,1.50

In [10]:
fill_hail_reports = hail_reports
fill_hail_reports

,BEGIN,END,EVENT_TYPE,BEGIN_LAT,BEGIN_LON,END_LAT,END_LON,MAGNITUDE
1865,195509221610,195509221610,Hail,38.70,-94.08,NaN,NaN,1.50
1868,195507191330,195507191330,Hail,30.50,-87.90,NaN,NaN,0.75
1875,195510281645,195510281645,Hail,33.28,-86.78,NaN,NaN,2.00
1879,195506121700,195506121700,Hail,37.08,-107.80,NaN,NaN,1.00
1882,195505071845,195505071845,Hail,37.08,-94.68,NaN,NaN,1.75
...,...,...,...,...,...,...,...,...
1168917,202407061246,202407061246,Hail,40.58,-99.38,40.58,-99.38,1.75
1168918,202407061520,202407061520,Hail,40.32,-98.90,40.32,-98.90,0.75
1168944,202407061255,202407061255,Hail,40.55,-99.32,40.55,-99.32,2.00
1168953,202407061258,202407061258,Hail,40.71,-99.88,40.71,-99.88,1.00
1168955,202407061645,202407061645,Hail,40.54,-97.59,40.54,-97.59,1.50

In [11]:
fill_hail_reports['END_LAT'] = (
    fill_hail_reports['END_LAT']
      .fillna(fill_hail_reports['BEGIN_LAT'])
)
fill_hail_reports['END_LON'] = (
    fill_hail_reports['END_LON']
      .fillna(fill_hail_reports['BEGIN_LON'])
)
fill_hail_reports

/var/folders/m8/6vszwx195fl9598f558j20ph0000gn/T/ipykernel_3691/77819830.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fill_hail_reports['END_LAT'] = (
/var/folders/m8/6vszwx195fl9598f558j20ph0000gn/T/ipykernel_3691/77819830.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fill_hail_reports['END_LON'] = (

,BEGIN,END,EVENT_TYPE,BEGIN_LAT,BEGIN_LON,END_LAT,END_LON,MAGNITUDE
1865,195509221610,195509221610,Hail,38.70,-94.08,38.70,-94.08,1.50
1868,195507191330,195507191330,Hail,30.50,-87.90,30.50,-87.90,0.75
1875,195510281645,195510281645,Hail,33.28,-86.78,33.28,-86.78,2.00
1879,195506121700,195506121700,Hail,37.08,-107.80,37.08,-107.80,1.00
1882,195505071845,195505071845,Hail,37.08,-94.68,37.08,-94.68,1.75
...,...,...,...,...,...,...,...,...
1168917,202407061246,202407061246,Hail,40.58,-99.38,40.58,-99.38,1.75
1168918,202407061520,202407061520,Hail,40.32,-98.90,40.32,-98.90,0.75
1168944,202407061255,202407061255,Hail,40.55,-99.32,40.55,-99.32,2.00
1168953,202407061258,202407061258,Hail,40.71,-99.88,40.71,-99.88,1.00
1168955,202407061645,202407061645,Hail,40.54,-97.59,40.54,-97.59,1.50

In [13]:
filtered_hail_reports= fill_hail_reports.dropna()
filtered_hail_reports

,BEGIN,END,EVENT_TYPE,BEGIN_LAT,BEGIN_LON,END_LAT,END_LON,MAGNITUDE
1865,195509221610,195509221610,Hail,38.70,-94.08,38.70,-94.08,1.50
1868,195507191330,195507191330,Hail,30.50,-87.90,30.50,-87.90,0.75
1875,195510281645,195510281645,Hail,33.28,-86.78,33.28,-86.78,2.00
1879,195506121700,195506121700,Hail,37.08,-107.80,37.08,-107.80,1.00
1882,195505071845,195505071845,Hail,37.08,-94.68,37.08,-94.68,1.75
...,...,...,...,...,...,...,...,...
1168917,202407061246,202407061246,Hail,40.58,-99.38,40.58,-99.38,1.75
1168918,202407061520,202407061520,Hail,40.32,-98.90,40.32,-98.90,0.75
1168944,202407061255,202407061255,Hail,40.55,-99.32,40.55,-99.32,2.00
1168953,202407061258,202407061258,Hail,40.71,-99.88,40.71,-99.88,1.00
1168955,202407061645,202407061645,Hail,40.54,-97.59,40.54,-97.59,1.50

In [39]:
filtered_hail_reports['LAT'] = filtered_hail_reports[['BEGIN_LAT','END_LAT']].mean(axis=1)
filtered_hail_reports['LON'] = filtered_hail_reports[['BEGIN_LON','END_LON']].mean(axis=1)

/var/folders/m8/6vszwx195fl9598f558j20ph0000gn/T/ipykernel_3691/344468623.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_hail_reports['LAT'] = filtered_hail_reports[['BEGIN_LAT','END_LAT']].mean(axis=1)
/var/folders/m8/6vszwx195fl9598f558j20ph0000gn/T/ipykernel_3691/344468623.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_hail_reports['LON'] = filtered_hail_reports[['BEGIN_LON','END_LON']].mean(axis=1)

## Comparision

In [15]:
hail_convective_path = '/Users/jimnguyen/IRMII/SCS_API/convective_outlooks/2024/12/forecast_day1'

In [ ]:
combined_hail_outlooks = []
for i in range()
    hail_gdf = gpd.read_file('/Users/jimnguyen/IRMII/SCS_API/convective_outlooks/2024/1/forecast_day1/day1otlk_20240111_1200/day1otlk_20240111_1200_hail.shp')

In [ ]:
from pathlib import Path
import geopandas as gpd
import pandas as pd
hail_convective_path = Path('/Users/jimnguyen/IRMII/SCS_API/convective_outlooks/2024/12/forecast_day1')

shp_paths = list(hail_convective_path.glob('*1200/*.shp'))

gdfs = [gpd.read_file(p) for p in shp_paths]
all_hail = gpd.GeoDataFrame(
    pd.concat(gdfs, ignore_index=True),
    crs=gdfs[0].crs
)

print(f"Found {len(shp_paths)} shapefiles; combined GeoDataFrame has {len(all_hail)} records.")

In [23]:
all_hail.dropna()

,DN,geometry,VALID,EXPIRE,ISSUE,LABEL,LABEL2,stroke,fill
6,2,"POLYGON ((-98.42812 26.00982, -98.48 27.04, -9...",202412031200,202412041200,202412030531,TSTM,General Thunderstorms Risk,#55BB55,#C1E9C1
8,2,"MULTIPOLYGON (((-90.39 39.31, -87.58 39.41, -8...",202412151200,202412161200,202412150544,TSTM,General Thunderstorms Risk,#55BB55,#C1E9C1
9,3,"POLYGON ((-97.38 34.13, -96.2 35.23, -95.38 35...",202412151200,202412161200,202412150544,MRGL,Marginal Risk,#005500,#66A366
11,5,"POLYGON ((-97.38 34.13, -96.2 35.23, -95.38 35...",202412151200,202412161200,202412150544,0.05,5% Hail Risk,#70380f,#9d4e15
17,2,"MULTIPOLYGON (((-94.31 35.88, -93.22 34.71, -9...",202412231200,202412241200,202412230517,TSTM,General Thunderstorms Risk,#55BB55,#C1E9C1
...,...,...,...,...,...,...,...,...,...
220,3,"POLYGON ((-95.79 34.34, -94.54 34.72, -93.27 3...",202412171200,202412181200,202412170545,MRGL,Marginal Risk,#005500,#66A366
221,5,"POLYGON ((-95.44 34.24, -93.54 34.71, -91.39 3...",202412171200,202412181200,202412170545,0.05,5% Wind Risk,#70380f,#9d4e15
234,2,"POLYGON ((-124.23148 45.31599, -123.9 45.16, -...",202412211200,202412221200,202412210526,TSTM,General Thunderstorms Risk,#55BB55,#C1E9C1
242,2,"POLYGON ((-124.73773 42.6733, -124.08 42.18, -...",202412201200,202412211200,202412200510,TSTM,General Thunderstorms Risk,#55BB55,#C1E9C1
248,2,"MULTIPOLYGON (((-101.53596 29.55736, -98.2 33....",202412161200,202412171200,202412160554,TSTM,General Thunderstorms Risk,#55BB55,#C1E9C1

**This code below should be getting all of the shp files from all years but it is just taking forever**

In [33]:
from pathlib import Path
import geopandas as gpd

base = Path('/Users/jimnguyen/IRMII/SCS_API/convective_outlooks')

shp_paths = list(
    base.glob('[0-9]*/*/forecast_day1/*1200/*.shp')
)

print(f"Found {len(shp_paths)} shapefiles in all years/months.")

gdfs = [gpd.read_file(p) for p in shp_paths]
all_hail = gpd.GeoDataFrame(
    pd.concat(gdfs, ignore_index=True),
    crs=gdfs[0].crs
)
print(f"Combined GeoDataFrame has {len(all_hail)} features.")

Found 18228 shapefiles in all years/months.

KeyboardInterrupt:

# Read 2024

In [60]:
from pathlib import Path
import geopandas as gpd
import pandas as pd

base = Path('/Users/jimnguyen/IRMII/SCS_API/convective_outlooks/2024')

shp_paths = list(
    base.glob('[0-9]/forecast_day1/*1200/*hail.shp')
)

print(f"Found {len(shp_paths)} shapefiles in all years/months.")

gdfs = [gpd.read_file(p) for p in shp_paths]
hail_outlook_24 = gpd.GeoDataFrame(
    pd.concat(gdfs, ignore_index=True),
    crs=gdfs[0].crs
)
print(f"Combined GeoDataFrame has {len(all_hail)} features.")

Found 548 shapefiles in all years/months.
Combined GeoDataFrame has 250 features.

In [61]:
hail_outlook_24 = hail_outlook_24.dropna()

In [62]:
for col in ['VALID','EXPIRE','ISSUE']:
    hail_outlook_24[col] = pd.to_datetime(
        hail_outlook_24[col].astype(str),
        format='%Y%m%d%H%M'
    )
hail_outlook_24

,DN,geometry,VALID,EXPIRE,ISSUE,LABEL,LABEL2,stroke,fill
1,5,"MULTIPOLYGON (((-99.21551 49.18204, -100.18 48...",2024-09-16 12:00:00,2024-09-17 12:00:00,2024-09-16 05:56:00,0.05,5% Hail Risk,#70380f,#9d4e15
2,15,"POLYGON ((-94.40081 48.98027, -96.95 47.76, -9...",2024-09-16 12:00:00,2024-09-17 12:00:00,2024-09-16 05:56:00,0.15,15% Hail Risk,#DDAA00,#FFE066
4,5,"MULTIPOLYGON (((-88.65 40.22, -87.53 41.55, -8...",2024-09-20 12:00:00,2024-09-21 12:00:00,2024-09-20 05:26:00,0.05,5% Hail Risk,#70380f,#9d4e15
5,5,"MULTIPOLYGON (((-105.22435 30.55321, -104.86 3...",2024-09-21 12:00:00,2024-09-22 12:00:00,2024-09-21 05:50:00,0.05,5% Hail Risk,#70380f,#9d4e15
6,15,"POLYGON ((-102.68 35.78, -101.61 35.49, -101.3...",2024-09-21 12:00:00,2024-09-22 12:00:00,2024-09-21 05:50:00,0.15,15% Hail Risk,#DDAA00,#FFE066
...,...,...,...,...,...,...,...,...,...
767,15,"MULTIPOLYGON (((-101.39 40.42, -100.54 40.87, ...",2024-05-03 12:00:00,2024-05-04 12:00:00,2024-05-03 05:55:00,0.15,15% Hail Risk,#DDAA00,#FFE066
768,10,"POLYGON ((-101.7 31.55, -101.88 32.68, -101.95...",2024-05-03 12:00:00,2024-05-04 12:00:00,2024-05-03 05:55:00,SIGN,10% Significant Hail Risk,#000000,#888888
769,10,"POLYGON ((-101.7 31.55, -101.88 32.68, -101.95...",2024-05-03 12:00:00,2024-05-04 12:00:00,2024-05-03 05:55:00,SIGN,10% Significant Hail Risk,#000000,#888888
771,5,"MULTIPOLYGON (((-103.09201 28.86228, -103.2 32...",2024-05-15 12:00:00,2024-05-16 12:00:00,2024-05-15 05:59:00,0.05,5% Hail Risk,#70380f,#9d4e15
772,15,"MULTIPOLYGON (((-99.5 34.87, -100.77 34.57, -1...",2024-05-15 12:00:00,2024-05-16 12:00:00,2024-05-15 05:59:00,0.15,15% Hail Risk,#DDAA00,#FFE066

In [41]:
filtered_hail_reports_24

,BEGIN,END,EVENT_TYPE,BEGIN_LAT,BEGIN_LON,END_LAT,END_LON,MAGNITUDE,LAT,LON
1865,195509221610,195509221610,Hail,38.70,-94.08,38.70,-94.08,1.50,38.70,-94.08
1868,195507191330,195507191330,Hail,30.50,-87.90,30.50,-87.90,0.75,30.50,-87.90
1875,195510281645,195510281645,Hail,33.28,-86.78,33.28,-86.78,2.00,33.28,-86.78
1879,195506121700,195506121700,Hail,37.08,-107.80,37.08,-107.80,1.00,37.08,-107.80
1882,195505071845,195505071845,Hail,37.08,-94.68,37.08,-94.68,1.75,37.08,-94.68
...,...,...,...,...,...,...,...,...,...,...
1168917,202407061246,202407061246,Hail,40.58,-99.38,40.58,-99.38,1.75,40.58,-99.38
1168918,202407061520,202407061520,Hail,40.32,-98.90,40.32,-98.90,0.75,40.32,-98.90
1168944,202407061255,202407061255,Hail,40.55,-99.32,40.55,-99.32,2.00,40.55,-99.32
1168953,202407061258,202407061258,Hail,40.71,-99.88,40.71,-99.88,1.00,40.71,-99.88
1168955,202407061645,202407061645,Hail,40.54,-97.59,40.54,-97.59,1.50,40.54,-97.59

In [42]:
import geopandas as gpd
import pandas as pd
from shapely.geometry import Point

for col in ['BEGIN','END']:
    filtered_hail_reports[col] = pd.to_datetime(
        filtered_hail_reports[col].astype(str),
        format='%Y%m%d%H%M'
    )

mask = (
    (filtered_hail_reports['BEGIN'].dt.year == 2024) |
    (filtered_hail_reports['END'  ].dt.year == 2024)
)

filtered_hail_reports_24 = filtered_hail_reports.loc[mask].copy()

/var/folders/m8/6vszwx195fl9598f558j20ph0000gn/T/ipykernel_3691/2165109932.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_hail_reports[col] = pd.to_datetime(
/var/folders/m8/6vszwx195fl9598f558j20ph0000gn/T/ipykernel_3691/2165109932.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_hail_reports[col] = pd.to_datetime(

In [69]:
filtered_hail_reports_24

,BEGIN,END,EVENT_TYPE,BEGIN_LAT,BEGIN_LON,END_LAT,END_LON,MAGNITUDE,LAT,LON
1132174,2024-05-23 19:47:00,2024-05-23 19:47:00,Hail,34.638,-99.2167,34.638,-99.2167,1.50,34.638,-99.2167
1132178,2024-05-14 15:10:00,2024-05-14 15:15:00,Hail,34.510,-88.2100,34.510,-88.2100,1.00,34.510,-88.2100
1132179,2024-05-14 13:52:00,2024-05-14 13:57:00,Hail,35.200,-88.2400,35.200,-88.2400,0.88,35.200,-88.2400
1132184,2024-06-15 19:24:00,2024-06-15 19:27:00,Hail,46.620,-101.9100,46.620,-101.9100,1.50,46.620,-101.9100
1132185,2024-06-02 14:30:00,2024-06-02 14:33:00,Hail,46.390,-99.4900,46.390,-99.4900,1.00,46.390,-99.4900
...,...,...,...,...,...,...,...,...,...,...
1168917,2024-07-06 12:46:00,2024-07-06 12:46:00,Hail,40.580,-99.3800,40.580,-99.3800,1.75,40.580,-99.3800
1168918,2024-07-06 15:20:00,2024-07-06 15:20:00,Hail,40.320,-98.9000,40.320,-98.9000,0.75,40.320,-98.9000
1168944,2024-07-06 12:55:00,2024-07-06 12:55:00,Hail,40.550,-99.3200,40.550,-99.3200,2.00,40.550,-99.3200
1168953,2024-07-06 12:58:00,2024-07-06 12:58:00,Hail,40.710,-99.8800,40.710,-99.8800,1.00,40.710,-99.8800
1168955,2024-07-06 16:45:00,2024-07-06 16:45:00,Hail,40.540,-97.5900,40.540,-97.5900,1.50,40.540,-97.5900

In [70]:
import geopandas as gpd

filtered_hail_reports_24_gdf = gpd.GeoDataFrame(
    filtered_hail_reports_24,
    geometry=gpd.points_from_xy(
        filtered_hail_reports_24['LON'],
        filtered_hail_reports_24['LAT']
    ),
    crs="EPSG:4326"
)

In [71]:
filtered_hail_reports_24_gdf

,BEGIN,END,EVENT_TYPE,BEGIN_LAT,BEGIN_LON,END_LAT,END_LON,MAGNITUDE,LAT,LON,geometry
1132174,2024-05-23 19:47:00,2024-05-23 19:47:00,Hail,34.638,-99.2167,34.638,-99.2167,1.50,34.638,-99.2167,POINT (-99.2167 34.638)
1132178,2024-05-14 15:10:00,2024-05-14 15:15:00,Hail,34.510,-88.2100,34.510,-88.2100,1.00,34.510,-88.2100,POINT (-88.21 34.51)
1132179,2024-05-14 13:52:00,2024-05-14 13:57:00,Hail,35.200,-88.2400,35.200,-88.2400,0.88,35.200,-88.2400,POINT (-88.24 35.2)
1132184,2024-06-15 19:24:00,2024-06-15 19:27:00,Hail,46.620,-101.9100,46.620,-101.9100,1.50,46.620,-101.9100,POINT (-101.91 46.62)
1132185,2024-06-02 14:30:00,2024-06-02 14:33:00,Hail,46.390,-99.4900,46.390,-99.4900,1.00,46.390,-99.4900,POINT (-99.49 46.39)
...,...,...,...,...,...,...,...,...,...,...,...
1168917,2024-07-06 12:46:00,2024-07-06 12:46:00,Hail,40.580,-99.3800,40.580,-99.3800,1.75,40.580,-99.3800,POINT (-99.38 40.58)
1168918,2024-07-06 15:20:00,2024-07-06 15:20:00,Hail,40.320,-98.9000,40.320,-98.9000,0.75,40.320,-98.9000,POINT (-98.9 40.32)
1168944,2024-07-06 12:55:00,2024-07-06 12:55:00,Hail,40.550,-99.3200,40.550,-99.3200,2.00,40.550,-99.3200,POINT (-99.32 40.55)
1168953,2024-07-06 12:58:00,2024-07-06 12:58:00,Hail,40.710,-99.8800,40.710,-99.8800,1.00,40.710,-99.8800,POINT (-99.88 40.71)
1168955,2024-07-06 16:45:00,2024-07-06 16:45:00,Hail,40.540,-97.5900,40.540,-97.5900,1.50,40.540,-97.5900,POINT (-97.59 40.54)

In [105]:
import pandas as pd
import geopandas as gpd
from shapely.ops import unary_union
import numpy as np

for df, cols in [
    (hail_outlook_24,               ['VALID','EXPIRE']),
    (filtered_hail_reports_24_gdf,  ['BEGIN','END']),
]:
    for c in cols:
        df[c] = pd.to_datetime(df[c])

hail_outlook_24   = hail_outlook_24.set_crs("EPSG:4326", allow_override=True)
filtered_hail_reports_24_gdf = filtered_hail_reports_24_gdf.set_crs("EPSG:4326", allow_override=True)

#Group by the unique (VALID, EXPIRE) window
#Union the geometries of the outlooks that comes together
records = []
for (valid, expire), grp in hail_outlook_24.groupby(['VALID','EXPIRE']):
    # union of all risk-level polygons for this window
    union_poly = unary_union(grp.geometry.values)
    
    # temporal overlap: END ≥ valid  AND  BEGIN ≤ expire
    mask_time = (
        (filtered_hail_reports_24_gdf['END']   >= valid) &
        (filtered_hail_reports_24_gdf['BEGIN'] <= expire)
    )
    candidate_reports = filtered_hail_reports_24_gdf[mask_time]
    
    # spatial filter: points inside the *union* polygon
    hits = candidate_reports[candidate_reports.geometry.within(union_poly)]
    
    records.append({
        'VALID':    valid,
        'EXPIRE':   expire,
        'n_events': len(candidate_reports),
        'n_hits':   len(hits),
        'hit_rate': (len(hits) / len(candidate_reports)
                     if len(candidate_reports)>0 else np.nan),
        'geometry': union_poly
    })

outlook_verif_period = gpd.GeoDataFrame(records, crs="EPSG:4326")

total_events = outlook_verif_period['n_events'].sum()
total_hits   = outlook_verif_period['n_hits'].sum()
overall_hit  = total_hits / total_events

print(f"Unique forecast periods: {len(outlook_verif_period)}")
print(f"Total reports in valid windows: {total_events:,}")
print(f"Total hits: {total_hits:,} → overall hit rate = {overall_hit:.2%}")

outlook_verif_period.sort_values('VALID')

Unique forecast periods: 205
Total reports in valid windows: 8,682
Total hits: 7,093 → overall hit rate = 81.70%

,VALID,EXPIRE,n_events,n_hits,hit_rate,geometry
0,2024-01-08 12:00:00,2024-01-09 12:00:00,28,20,0.714286,"POLYGON ((-88.406 29.863, -88.432 29.714, -88...."
1,2024-01-09 12:00:00,2024-01-10 12:00:00,2,1,0.500000,"MULTIPOLYGON (((-87.6 31.08, -86.82 32, -84.85..."
2,2024-01-11 12:00:00,2024-01-12 12:00:00,33,18,0.545455,"POLYGON ((-97.75 30.14, -97.94 31.18, -97.48 3..."
3,2024-01-12 12:00:00,2024-01-13 12:00:00,0,0,NaN,"POLYGON ((-80.98281 31.03361, -82.17 30.21, -8..."
4,2024-01-23 12:00:00,2024-01-24 12:00:00,4,4,1.000000,"POLYGON ((-99.3 26.76, -99.61446 27.0463, -99...."
...,...,...,...,...,...,...
200,2024-09-20 12:00:00,2024-09-21 12:00:00,14,2,0.142857,"MULTIPOLYGON (((-99.55 38.31, -97.35 37.99, -9..."
201,2024-09-21 12:00:00,2024-09-22 12:00:00,45,34,0.755556,"MULTIPOLYGON (((-105.07 32.3, -105.46 33.99, -..."
202,2024-09-22 12:00:00,2024-09-23 12:00:00,1,0,0.000000,"POLYGON ((-104.08051 29.21675, -102.71 31.58, ..."
203,2024-09-23 12:00:00,2024-09-24 12:00:00,0,0,NaN,"POLYGON ((-92.09 37.59, -90.38 38.34, -89.43 3..."
204,2024-09-24 12:00:00,2024-09-25 12:00:00,96,80,0.833333,"MULTIPOLYGON (((-99.24 36.52, -98.07 36.65, -9..."

In [110]:
calib = (
    forecast_df
    .groupby('DN')
    .agg(
        n = ('y','size'),             # # of forecasts issued at this DN
        o = ('y','mean'),             # observed hit‐rate 
        p = ('p','first')             # nominal forecast prob
    )
    .reset_index()
    .sort_values('p')
)
calib['n'] = calib['n'].astype(int)


print("\nPer-DN calibration:")
print(calib[['DN','n','p','o']].to_string(index=False))

Per-DN calibration:
 DN   n    p        o
  5 205 0.05 0.809756
 10 138 0.10 0.942029
 15 119 0.15 0.873950
 30  32 0.30 0.937500
 45   5 0.45 1.000000

**Thats the accuracy/hitrate at each DN level btw**